### ISSUE TITLE
duplicate identifier issue

### ISSUE THREAD

**Issue by vgosain91** [gilf/angular2-indexeddb#5] opened 2016-11-24 13:34 UTC
The es6-promise folder in @types folder in node modules created by you package is creating duplicate identifier issues. If we remove it ,then i get "cannot resolve all paramters for AngularIndexedDb" in metadata resolver while running the application.

**Comment by gilf** [comment] 2016-11-27 09:33
Hi,
This is a duplicate of #4.

**Closed by gilf** 2016-11-27 09:33 UTC
